In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('../data/monthly datasets for each location/September.csv')

In [11]:
FILEPATH = '../data/locations/'
FILENAME = 'geospatial.csv'
geo_df = pd.read_csv(FILEPATH + FILENAME)

In [9]:
df.head(10)

,Solar Potential,Landcover,Soil Moisture,Soil Texture,Slope,Aspect
0,154.815897,5030.627445,0.213664,11853.450220,31.519659,28.801444
1,152.629103,2333.382047,0.234046,7449.897142,22.879574,118.691951
2,150.486632,2754.700458,0.213664,11025.815270,29.273340,37.270103
3,153.690789,3972.602137,0.210990,7635.981889,4.760822,92.626847
4,154.210562,4149.814222,0.210990,9220.060659,17.690387,80.913842
5,148.334960,0.000000,0.224990,3172.311284,29.420431,148.976753
6,151.803469,0.000000,0.212777,3587.370113,35.268259,172.446560
7,153.574444,2086.587694,0.212777,6031.618971,16.634002,80.109610
8,154.109736,5088.779720,0.215566,8620.567681,2.204745,149.866752
9,148.454748,0.000000,0.228703,2047.451234,15.744254,78.910653

In [13]:
newdf = pd.concat((geo_df[['Latitude', 'Longitude']], df), axis = 1)

In [14]:
newdf.head(10)

,Latitude,Longitude,Solar Potential,Landcover,Soil Moisture,Soil Texture,Slope,Aspect
0,38.93,46.58,154.815897,5030.627445,0.213664,11853.450220,31.519659,28.801444
1,38.97,46.58,152.629103,2333.382047,0.234046,7449.897142,22.879574,118.691951
2,38.97,46.50,150.486632,2754.700458,0.213664,11025.815270,29.273340,37.270103
3,38.97,46.62,153.690789,3972.602137,0.210990,7635.981889,4.760822,92.626847
4,38.97,46.66,154.210562,4149.814222,0.210990,9220.060659,17.690387,80.913842
5,39.01,46.58,148.334960,0.000000,0.224990,3172.311284,29.420431,148.976753
6,39.01,46.62,151.803469,0.000000,0.212777,3587.370113,35.268259,172.446560
7,39.01,46.66,153.574444,2086.587694,0.212777,6031.618971,16.634002,80.109610
8,39.01,46.70,154.109736,5088.779720,0.215566,8620.567681,2.204745,149.866752
9,39.05,46.58,148.454748,0.000000,0.228703,2047.451234,15.744254,78.910653

In [40]:
df

,Latitude,Longitude,Elevation,Distance from Armenia,Slope,landcover_10,landcover_20,landcover_30,landcover_40,landcover_50,...,Soil Moisture,Soil Temperature,b0_0,b0_1,b0_4,b0_5,b0_6,b0_7,b0_9,Aspect
0,38.93,46.58,2944,4.592230,31.519659,5030.627445,18336.252690,0.000000,6683.010795,86891.097460,...,0.213664,292.579437,87088.19760,98844.27183,942.041732,85077.81331,128884.27110,0.000000,11853.450220,28.801444
1,38.97,46.58,2756,4.461349,22.879574,2333.382047,15324.649390,0.000000,4978.872489,83997.130590,...,0.234046,291.694611,84296.84740,95038.49995,505.381565,81330.52993,124498.57710,0.000000,7449.897142,118.691951
2,38.97,46.50,2872,1.512298,29.273340,2754.700458,21270.570190,0.000000,11894.978200,89443.919990,...,0.213664,292.579437,89866.55624,98860.83868,6410.808309,85333.65598,125852.16350,0.000000,11025.815270,37.270103
3,38.97,46.62,2783,7.368732,4.760822,3972.602137,12723.262620,0.000000,1520.833922,81356.007830,...,0.210990,295.879028,81587.85193,93259.03083,0.000000,79477.23039,123958.74790,1847.886281,7635.981889,92.626847
4,38.97,46.66,2959,10.611305,17.690387,4149.814222,10621.036290,0.000000,1937.265029,78777.127740,...,0.210990,295.879028,78936.40489,91574.27133,1937.265029,77732.32639,123511.89190,0.000000,9220.060659,80.913842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,40.49,47.10,121,99.322624,2.218858,5666.707668,0.000000,5702.424080,1656.249463,4698.326563,...,0.218501,296.781982,43125.96706,88633.72761,1656.249463,71978.06323,51002.11966,0.000000,48783.440790,92.626847
981,40.49,47.22,111,109.216905,4.586683,3662.918385,0.000000,3232.622012,1001.148239,7943.303719,...,0.221687,296.966675,37571.84780,88572.68517,3189.916858,72663.41516,56019.83423,0.000000,55008.283620,55.373158
982,40.49,47.26,85,112.525667,1.219365,6598.060728,1164.722052,5334.089428,0.000000,8307.516491,...,0.221687,296.966675,36169.27001,88813.41938,0.000000,73206.72005,57993.75682,968.526380,57334.912060,87.373153
983,40.53,47.18,34,106.971914,0.000000,6884.912427,2455.022644,1499.982333,0.000000,9896.786907,...,0.207933,297.150452,43079.92937,92909.69042,2455.022644,76706.36639,58032.69145,0.000000,56303.510430,182.626847
984,40.53,47.22,23,110.242031,2.219258,7390.754523,0.000000,1674.203824,1590.234728,11893.745770,...,0.217952,297.157379,41587.74824,93014.77078,0.000000,77071.27235,59746.97591,2645.371117,58380.777530,149.288418